services:
  postgres:
    image: postgres:15
    container_name: fia-postgres
    environment:
      POSTGRES_DB: fia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:
